version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aplicacion_senas
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://appuser:secret@db:5432/aplicacion_senas
      SECRET_KEY: change-this-secret-in-prod
    ports:
      - "8000:8000"

volumes:
  db-data:
